package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selectors.withText;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Check open page OZON Travel")
    @DisplayName("open page OZON Travel")
    void checkHeaderTest() {
        step("Открыть https://www.ozon.ru/", () -> {
            open("https://www.ozon.ru/");
        });
        step("Перейти на страницу OZON TRAVEL", () -> {
            $(By.partialLinkText("Travel")).click();
        });
        step("Проверить заголовок Покупать авиа- и ж/д билеты на Ozon удобно!", () -> {
            $("#__ozon").shouldHave(text("Покупать авиа- и ж/д билеты на Ozon удобно!"));
        });
    }


    @Test
    @Description("Check header Tab avia")
    @DisplayName("Check header Tab avia")
    void checkHeaderTabAviaTest() {
        step("Open url 'https://www.ozon.ru/travel/'", () ->
                open("https://www.ozon.ru/travel/"));

        step("Проверить, что на странице есть вкладка Авиабилеты", () -> {
            $(".ui-q1").shouldHave(text("Авиабилеты"));
        });

        step("Открыть вкладку Авиабилеты", () -> {
            $(".ui-q1").$(withText("Авиабилеты")).click();
        });

        step("Проверить заголовок на вкладке Авиабилеты - Поиск дешёвых авиабилетов", () -> {
            $(".aay8").shouldHave(text("Поиск дешёвых авиабилетов"));
        });
    }

    @Test
    @Description("Check header Tab Railway")
    @DisplayName("Check header Tab Railway")
    void checkHeaderTabRailwayTest() {
        step("Open url 'https://www.ozon.ru/travel/'", () ->
                open("https://www.ozon.ru/travel/"));

        step("Проверить, что на странице есть вкладка ЖД билеты", () -> {
            $(".ui-q1").shouldHave(text("ЖД билеты"));
        });

        step("Открыть вкладку ЖД билеты", () -> {
            $(".ui-q1").$(withText("ЖД билеты")).click();
        });

        step("Проверить заголовок на вкладке ЖД билеты - Жд билеты на поезд", () -> {
            $(".aay8").shouldHave(text("Жд билеты на поезд"));
        });
    }

    @Test
    @Description("Check header Tab Hotels")
    @DisplayName("Check header Tab Hotels")
    void checkHeaderTabHotelsTest() {
        step("Open url 'https://www.ozon.ru/travel/'", () ->
                open("https://www.ozon.ru/travel/"));

        step("Проверить, что на странице есть вкладка Отели", () -> {
            $(".ui-q1").shouldHave(text("Отели"));
        });

        step("Открыть вкладку Отели", () -> {
            $(".ui-q1").$(withText("Отели")).click();
        });

        step("Проверить заголовок на вкладке Отели - Бронирование отелей и гостиниц", () -> {
            $(".aay8").shouldHave(text("Бронирование отелей и гостиниц"));
        });

    }



    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.ozon.ru/'", () ->
                open("https://www.ozon.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}